FROM node:20-alpine

WORKDIR /app

ARG API_BASE_URL
ENV API_BASE_URL=$API_BASE_URL
ARG VIS_API_BASE_URL
ENV VIS_API_BASE_URL=$VIS_API_BASE_URL

COPY ui/package.json /app/package.json
RUN npm install

COPY ui /app
RUN npm run build \
  && mkdir -p /app/.next/standalone/.next \
  && cp -r /app/.next/static /app/.next/standalone/.next/static

EXPOSE 3000
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
CMD ["node", "/app/.next/standalone/server.js"]
